### ISSUE TITLE
Roll command?

### ISSUE THREAD

**Issue by MrKyRy** [HollywoodHeists/public#100]
Any chance we can get a /roll command to allow us to use the odds for RP or a command that will allow us to give us odds to help our character make a choice and go with it? Example being my character needs to make a choice and I roll to see what he does.

**Comment by Montana-77** [comment]
This has been apart of the plan for a while! TY for the post will look to get this implemented as soon as we can.

**Comment by Bergsbrew** [comment]
Can't wait to see how huge Willy's Willy is

**Comment by DeliriousHoot** [comment]
> Can't wait to see how huge Willy's Willy is

1/12

**Comment by AliAliJr** [comment]
Added.
