### ISSUE TITLE
payment options- barbers/clothing stores

### ISSUE THREAD

**Issue by xxtraspicyy** [HollywoodHeists/public#103]
I think there should be an option for either cash or card payment, must have bank card to be able to pay by card obviously. 
I understand the intent for having to have cash on you i guess for robberies if thats a thing, but its also not overly realistic to have to pay cash at all outlets. just a thought.

**Comment by Colt-Sterling** [comment]
Totally agree. I have walked into those shops with no cash too many times lol. So I like the idea of being able to use cash or card. In the future the plan is to make saving an outfit be the only part that costs money so we can alleviate some of the headache of just wanting to get new glasses, a new shirt, or whatever you're after.

**Comment by AliAliJr** [comment]
Added bank as a primary payment option.
