### ISSUE TITLE
casino burger

### ISSUE THREAD

**Issue by Meelokbruvv** [HollywoodHeists/public#105]
![image](https://user-images.githubusercontent.com/104778184/212210466-d8486c99-fdfc-4530-84a3-b2403a1f3145.png)

so i won 10 casino burgers from the wheel under the random slot on the wheel and they currently don't work.

**Comment by MrKyRy** [comment]
It's because burgershot is better

**Comment by AliAliJr** [comment]
you need to sit one of the casino bar chair to consume casino food.
