### ISSUE TITLE
trucker job bug

### ISSUE THREAD

**Issue by KosimaGhost** [HollywoodHeists/public#111]
![truckerjob](https://user-images.githubusercontent.com/121804141/212394667-748b96a2-7f46-493e-b7cb-c69e12f74fb9.png)

This error comes up sometimes when doing the trucker job and it crashes your game. The issue with that is that when you've been doing it it for a while, you lose your paycheck completely. I probably sadly lost about 3 hours of my time which would amount to about 9k altogether. I'm not too stressed about it but I thought I'd mention it so it doesn't happen to someone else, amd so you guys are aware.

Happy Friday !

**Comment by AliAliJr** [comment]
Fixed thanks for reporting.
