### ISSUE TITLE
Taxi driving meter for players

### ISSUE THREAD

**Issue by KosimaGhost** [HollywoodHeists/public#118]
There is currently no way to reset the meter yourself, the only way it resets is when you pick up a local. So when you pick up an actual player, you can start the meter but there is no way to reset it if you're picking someone else up afterward, unless you've done an NPC one inbetween.
Because of that I can't give them an accurate fare and end up just telling people to pay me whatever they think is fair, which is fine, but I think if we had a way to reset it, it'd be easier to RP it out. Or an invoice system could also be cool. But really just being able to restart the meter would be a huge improvement.

Thanks again, sorry for bothering you haha.

**Comment by Montana-77** [comment]
Not bothering at all!   Thank you for the post!  Will definitely look into this soon.

**Comment by AliAliJr** [comment]
Reset option added in Radial Menu.
