### ISSUE TITLE
Fishing Return Boat Issue

### ISSUE THREAD

**Issue by Stagonium** [HollywoodHeists/public#12]
### Discussed in https://github.com/HollywoodHeists/public/discussions/5

<div type='discussions-op-text'>

<sup>Originally posted by **MrKyRy** December 16, 2022</sup>
When attempting to return the boat you rented, the boat does not disappear (unsure if there is a specified radius or area it needs to be in order for it to be returned but is not specified). Unsure if you are also supposed to get money back or not, but you do not get any money back. (Assuming the 500 is for the rent fee and that money goes away) </div>

**Comment by Stagonium** [comment]
were you renting from the guy at the marina at 356 or the fishing guy on the beach by the pier?

**Comment by MrKyRy** [comment]
I was renting from the fishing guy on the beach near the canal entrance
