### ISSUE TITLE
Taxi fare unlimited

### ISSUE THREAD

**Issue by DeliriousHoot** [HollywoodHeists/public#120]
Currently if you're doing an NPC job it seems as though you can just run the fare up, which while is a thing IRL should probably be limited to some degree as I could pick up someone and drive around the island for hours making way more money than I otherwise should be. (the taxi buff was needed, but the unlimited fare needs to be capped).

**Comment by K-Reynolds** [comment]
You actually can't, it is capped. I tried running the fare a little too much and the NPC told me "You tried to scam me  I'm only.paying $600".
