### ISSUE TITLE
Tracking work accomplished after crashing

### ISSUE THREAD

**Issue by wetweebs** [HollywoodHeists/public#121]
I know a crashing bug for trucking was recently fixed (not sure if that fix is currently in effect) but I crashed while trucking at the time of posting. this got me thinking that the main issue (besides just that crashing is annoying) is that you lose all work progress upon 'leaving.' so taking the truck back to get the deposit and then the paycheck says 'you have not done any work' and you've now wasted that time. If there is a way to make the work paycheck persist through the event of a crash/leaving momentarily that would be fantastic. though i understand if there is a technical reason that this would not work.

**Comment by AliAliJr** [comment]
can u explain, what you were doing when crash occurs. (collecting package, delivering package, or just driving?)

**Comment by wetweebs** [comment]
> can u explain, what you were doing when crash occurs. (collecting package, delivering package, or just driving?)

At the time I was crashing when delivering packages (something about the progress bar I believe). Pretty sure this has since been fixed. The main thing was hoping there would be some way to keep the "clocked hours” so to speak through disconnecting and rejoining. 

Example: doing an hour worth of deliveries and then needing to relog (crashing or otherwise) and then not getting paid after you come back

**Comment by AliAliJr** [comment]
Issue was related to prop, its fixed thanks for reporting.
