### ISSUE TITLE
Smelting Diamonds

### ISSUE THREAD

**Issue by iTzaDeAdHoBo** [HollywoodHeists/public#123]
so i got 10 diamond rings from recycling after being there for a good while and i smelted them down and got 10 diamonds and 10 gold bars, but theres no where to sell them (unless i just dont know where) ive tried going down to mining and he wouldnt take either one, ive gone to the pawn shop nothing, and ive tried some of the other non normal pawn shops nothing.

**Comment by AliAliJr** [comment]
you can sell them to pawnshop.
