### ISSUE TITLE
car customization after being stolen

### ISSUE THREAD

**Issue by DeliriousHoot** [HollywoodHeists/public#124]
Currently if someone steals your car and does customization to it that sticks to the car even after you get it back. if we're going to make it so easy to steal people's cars then the customizations done to it by someone else need to drop off after pulling car out of the garage again otherwise people can just go around and steal cars, fuck with the customization just to troll and force you to spend money to fix it.

**Comment by RockemRobotics** [comment]
I dunno, I feel like this falls within RP. It's not like they can change the customization on your car for free, they are spending money to do it. You can easily roll it into an RP story if it happens to you.

**Comment by DeliriousHoot** [comment]
yeaaaaa no. too easy to troll with and abuse.

**Comment by Rivallrelyks** [comment]
This is a common troll and way of antagonizing in public servers. taking it away would be silly because it can b used as funny and good ways (anything can be abused, punish the abusers, don't remove the system) . 
just for an example if someone stole my car and did this i would 
1. call the cops 
2. once the car is back in my possession take it to a garage and get a quote to fix the changes.
3. use that receipt to sue the criminals 
4. ????
5. profit

**Comment by Stagonium** [comment]
IF this can be done without people who don't own the car modifying the actual performance upgrades, id be okay with it, but if i spend 15k on a turbo and you steal my car for 200 worth of lockpicks and just go remove it for FREE, with no benefit to yourself, you are a monster and that's not cool to me

**Comment by DeliriousHoot** [comment]
I'm not even saying remove it entirely, I'm saying have the car reset when it gets put in the garage back to what it was before.

**Comment by ItsTrihawk** [comment]
What about like a "warranty" period of 48 hours of being able to revert your car to its previous state after modifications were made by a 3rd party?

**Comment by RockemRobotics** [comment]
> IF this can be done without people who don't own the car modifying the actual performance upgrades, id be okay with it

Yeah, this is the big one. Changing cosmetics is funny and cheeky, changing performance upgrades is a dick move unless it costs a lot.

**Comment by Montana-77** [comment]
Yeaaaa We don’t like stolen cars having the option to remove parts if someone chooses to be that toxic    Not sure what the answer is quite yet but definitely need some way to either not let anything besides cosmetics be changed or if upgrades are removable then we need the framework for the rp with suing the individual that did it.

**Comment by Midori33** [comment]
Is there an RP way that players could provide registration or mechanics could check to make sure that the owner of the car is actually the one they are dealing with? Or perhaps mechanics should probably just know RP wise that someone coming in and removing multiple mods might be a bit suspicious?

**Comment by ItsTrihawk** [comment]
Is it possible to make it where only visual modifications can be done without a mechanic? Leave all performance modifications to mechanics?

**Comment by YouTri** [comment]
> 
I like that perf mods can only be done by mechanics. It takes away a lot of rp if you can just do it like GTA Online. As for the stolen cars getting worked on maybe mechanics can have a database like the MDT but only for the DMV section to run the plates. All persons at the shop must present an ID when getting work done on the car

**Comment by AliAliJr** [comment]
already implemented, forgot to close.
