### ISSUE TITLE
Convenience store operator at 3012

### ISSUE THREAD

**Issue by RockemRobotics** [HollywoodHeists/public#127]
The poor gentleman working the store at 3012 in Paleto Bay has no legs and yet doesn't have reasonable accommodations for his disability. Could we get him some legs or maybe a stool to support himself on?

![image](https://user-images.githubusercontent.com/14297779/212801451-2a6dedfc-a180-4bff-bb67-af3c37f6027a.png)

**Comment by Montana-77** [comment]
😂😂 poor guy.   We will definitely cater to his needs
