### ISSUE TITLE
Casino interior loading

### ISSUE THREAD

**Issue by Zoraketh** [HollywoodHeists/public#129]
The 2-3 times I have been to the casino, the interior loads kind of slow load or only loads part of the interior. Going in and out fixed some of it. But the wheel and slot machines did not load. It has happened on 2 different days now. Don't know what exactly is causing it. One of the times I was with someone and they also could not see any of the stuff inside.
![image](https://user-images.githubusercontent.com/92574732/212810096-82534fc9-ee8a-45ea-93e8-21503ba1aaaf.png)
![image](https://user-images.githubusercontent.com/92574732/212810483-e0fd0df8-5a28-45d2-a407-0bcc82fd5628.png)

**Comment by MrKennyG** [comment]
The fix i found is waiting before entering the door down the stairs. You get close to the door and you will see everything change over then walk through the doors.   (can confirm it is a glitch though)
