### ISSUE TITLE
Selling your car back to dealer at used car lot gives no confirmation prompt or lets you know the price

### ISSUE THREAD

**Issue by Rivallrelyks** [HollywoodHeists/public#132]
Just wanted to check what my car was valued to sell back , clicking "sell car for reduced price" instantly sells your car without giving you an are you sure prompt or letting you know what price. 
The are you sure prompt would be helpful if you misclick if your trying to put the car for public sale (player to player).
knowing the price would be helpful to gage how much you should be selling it for on the lot.
a solution would be having the sell back button have the same Car title screen as the public sale but already filled out, or something as simple as saying "are you sure yo would like to sell your car for 50% of original value"

**Comment by Montana-77** [comment]
Thank you for bringing this to light!! We will add a warning prompt for sure.

**Comment by AliAliJr** [comment]
Added.
