### ISSUE TITLE
Test drive cars

### ISSUE THREAD

**Issue by cvalenta44** [HollywoodHeists/public#133]
I've noticed in a handful of instances that you can test drive a vehicle and sometimes it will go past the allotted test drive time and you have to pull into the garage at PDM to click finish test drive. I know that it's happened with the Cadillac CTS-V, Subaru Impreza, Ram rebel, the Ford raptor and the Mercedes SLR McLaren. As far as I can tell it's not if you do a certain thing that will cause it to stick around.

**Comment by Colt-Sterling** [comment]
We will look in this. Thank you for the post!

**Comment by BaelyTV** [comment]
As i mentioned earlier @Colt-Sterling when walking into PDM from the south side entrance, the two podiums closest to the windows facing the west will allow you to test drive cars indefinitely. the two closes to the desk will end at 30 seconds and the one in the middle i have yet to test.

**Comment by cvalenta44** [comment]
I also noticed today that when test driving cars sometimes they get pulled out damaged or have engine problems. I tried with 4 different types of vehicles and 3 of the 4 would just stall as if there was a bunch of damage.

**Comment by DeliriousHoot** [comment]
This issue is not specific to which podium you are at btw, all of them can cause this bug to happen. I tested for this bug a lot in alpha and was never able to find a specific trigger as it doesn't always happen on demand
