### ISSUE TITLE
island cars

### ISSUE THREAD

**Issue by KosimaGhost** [HollywoodHeists/public#136]
Hey there!

So a while back I bought a rebel on the islandm, for the islandm, to do island stuff with. Nowe since the rework of garages, there is no longer a garage on the island, and the rust rebel ended up at pillbox garage.
Now, my question is this - will there be a garage again there in the future ? The island is quite big, and running everywhere back and forth gets a little tedious, but I'd understand wanting it that wasy, I just want to know if I can sell this extra rebel I dont need since I already owned one from the main island, or will there be a garage there again in the future that I can move it into ?
If there is going to be no garage on the island, will there be any other way at all to get around a bit faster on it ?

Thanks for all the hard work!

**Comment by AliAliJr** [comment]
Vehicle rental added on island.
