### ISSUE TITLE
offroad vehicle pricing

### ISSUE THREAD

**Issue by DeliriousHoot** [HollywoodHeists/public#137]
I noticed some of the pricing on the offroad trucks is kind of all over the place. you've got the Raptor which costs 420,000 which is a bit silly since it got nerfed quite a bit. personally I dont feel any of the trucks are overly fast and the prices should probably be all around the 100-160K mark like the Ram Rebel is. on the conversation of trucks I'd love to see some more get brought in. I've linked a few that I think would be cool and would add variety to the offroad section as currently we got like 4 or 5 jeeps in there which might be a bit much.

2019 GMC Sierra (https://www.gta5-mods.com/vehicles/2019-gmc-sierra-at4-add-on-fivem-templated-21-liveries)
2020 Chevy Silverado (https://www.gta5-mods.com/vehicles/2020-chevrolet-silverado-1500-crew-cab-trail-boss-lt)
2019 Nissan Titan Pro 4X (https://www.gta5-mods.com/vehicles/nissan-titan-crew-cab-xd-pro-4x-add-on-tuning)

**Comment by Colt-Sterling** [comment]
We'll be adjusting some existing prices as the new cars come rolling into the city.
