### ISSUE TITLE
Gas run error

### ISSUE THREAD

**Issue by silentgames96** [HollywoodHeists/public#14]
So did multiple gas runs but this certain area I think is bugged because of where the hangar is located it is overriding the truck deposit area. P.S. don't worry about the video quality, had to lower it to post.
 
https://user-images.githubusercontent.com/76965752/208490716-706f434e-3a04-44c5-aaa9-4ab3f83e73ba.mp4

**Comment by silentgames96** [comment]
this gas run stopped is currently not working aswell. 
![image](https://user-images.githubusercontent.com/76965752/208508062-e469d1cf-2e6b-4c72-a4b1-a9dd575a7705.png)

**Comment by Colt-Sterling** [comment]
Thanks for the heads up man! We'll look into it

**Comment by silentgames96** [comment]
Update: When doing gas runs, there is a Small, Medium, and Large Cargo run. The Small and Medium Cargo runs work but the Large one is the only one that doesn't work

**Comment by Montana-77** [comment]
Complete Gas script rework... Gas station owner ship is a part of the content drop in the coming weeks of the city launch.
