### ISSUE TITLE
Engine auto restarts after turning off/getting out

### ISSUE THREAD

**Issue by wetweebs** [HollywoodHeists/public#141]
idk if its just me or a key bind issue or what, but every time and with any vehicle if I turn off the engine it will automatically restart itself. Same thing happens if I just get out of the vehicle normally. It doesn't seem like any gas is being used but the engine noise and headlights remain on

**Comment by KosimaGhost** [comment]
It might very well be a keybinding issue, if you go in your FiveM settings you'll find 2 different enging on/off buttons, if they are both on the same keybind (which they were by default for me), it will cancel it out, I'd suggest checking it out !

**Comment by AliAliJr** [comment]
Fixed, Thanks for reporting, Hold F key while exiting vehicle, if u want to leave engine running.
