### ISSUE TITLE
SUBARU 2004 SUBARU IMPREZA WRX STI 

### ISSUE THREAD

**Issue by iTzaDeAdHoBo** [HollywoodHeists/public#146]
i just test drove a stock subaru at pdm and it goes 103 top, mine fully upgraded barely goes over 110. Is this something that can be fixed?

**Comment by RockemRobotics** [comment]
How are handling, acceleration, drift, etc? Upgrading should do far more than just increase your max speed.

**Comment by iTzaDeAdHoBo** [comment]
accel is a lil better but overall its almost the same as stock

**Comment by QuintenM911** [comment]
not to be a downer but most cars are supposed to be in that range of speed to keep it fair in the city right now

**Comment by Stagonium** [comment]
At least in vanilla gta, upgrading cars exclusively upgrades acceleration, and has no impact on top speed of a vehicle. The upgrades only help you reach a vehicles top speed faster.

**Comment by iTzaDeAdHoBo** [comment]
if thats the case is there anyway to get my money back for the upgrades, because its not really worth it and a waste if the car can do the same speed as one fresh off the lot at pdm

**Comment by Colt-Sterling** [comment]
> if thats the case is there anyway to get my money back for the upgrades, because its not really worth it and a waste if the car can do the same speed as one fresh off the lot at pdm

If you head down to 227 they'll probably buy the old parts off you for near market value if you'd like. But I'd recommend keeping most of them and maybe think about an engine swap? if you get the right one it can boost your performance considerably.
