### ISSUE TITLE
Wrong gun & Ammo poof

### ISSUE THREAD

**Issue by meeeuuuh** [HollywoodHeists/public#148]
When in the gun store in ammunation by Little Seoul, I bought a sns pistol and received a walther p99. Also my ammo poofed when I moved it in my inventory. Here is a clip: https://medal.tv/games/gta-v/clips/Sk1FYJBzPgWQQ/d1337NMmlRTI?invite=cr-MSxIdkosMTczMDA4MzAs Discord: meeeuuuh#6063

**edit: After watching the clip I realized I did not have enough "cash" for why I did not get the ammo. But still a little confused because when purchasing the gun it came out of my bank.

**Comment by AliAliJr** [comment]
issue is fixed thanks for reporting.
