### ISSUE TITLE
My lvl 5 fishing rod and lvl 1 net disappeared 

### ISSUE THREAD

**Issue by DerekMcKayy** [HollywoodHeists/public#149]
When i woke up in my apartment my rod and net was missing from my chest. I left the apt and when i went back in it asked me to move in. Went inside and theyre still missing. Anyway i can get those back? Thanks!

**Comment by DerekMcKayy** [comment]
MOVED APARTMENTS AND ITS WORKING NOW!

**Comment by AliAliJr** [comment]
^
