### ISSUE TITLE
Lost all inventory after prison escape

### ISSUE THREAD

**Issue by SharKingKong** [HollywoodHeists/public#154]
As the title says since i didn't check out with the CO I couldn't recover all my items. Broke back into prison to try and get out the right way, didn't get anything back still.

Not sure if this is intended or not.

**Comment by legacyReflex** [comment]
You broke out of prison bozo they aren't going to hand your stuff back over.

**Comment by Meelokbruvv** [comment]
![image](https://user-images.githubusercontent.com/104778184/215308969-753ae0a7-4d21-4250-bd1e-76565eede1b4.png)
