### ISSUE TITLE
Broom emote suggestion

### ISSUE THREAD

**Issue by lmlRockzlml** [HollywoodHeists/public#160]
Can we get a broom sweeping emote?
When working the slow shift alone at burgershot I spend my time cleaning. I clear tables, wipe down surfaces, clean the windows. I was trying to find a broom emote to sweep the floors inside and out of the restaurant.
It isnt a big suggestion but a sweeping the floors emote helps keep me from going crazy bored when there is no RP interaction.

**Comment by Colt-Sterling** [comment]
I believe we already have an emote with a broom? I think it's /e janitor or something along those lines.

**Comment by AliAliJr** [comment]
^
