### ISSUE TITLE
Engine Trouble

### ISSUE THREAD

**Issue by lmlRockzlml** [HollywoodHeists/public#166]
Is there any chance we can get some advanced repair kits in the city to fully fix the cars to 100% like it had a mechanic fix it. Even if it costs 2.5k I would pay it!!! The bennys fix and the bennys bench doesnt fix the engine. Im stalling a lot and after fixing the car, the engine still drops from perfect to red and I just cant get around the city all day until a mechanic gets on. Even if its just a tempory thing while the server grows. I BEG!!! (or hire me as a mechanic to fix my own car when ever I need lol)

**Comment by Colt-Sterling** [comment]
We can fs get this rolling! Those repair kits I gave you the other day only repair to a certain percentage, but we can bump that up till it feels like it's in a better place.
