### ISSUE TITLE
Food not getting rid of my hangry

### ISSUE THREAD

**Issue by InfiniteTenshi** [HollywoodHeists/public#169]
Today, when coming into the city I have been having trouble filling up my hunger. It only goes up about 1/20th of the food bar where water still fills up the normal amount.

**Comment by xxtraspicyy** [comment]
me also

**Comment by Meelokbruvv** [comment]
Is it just one food item or is it all different good Items?

**Comment by Stetty78** [comment]
working as intended. try food from local restaurants
