### ISSUE TITLE
Inventory thoughts 

### ISSUE THREAD

**Issue by ChugThis** [HollywoodHeists/public#17]
Howdy, open to thoughts and ideas on this! Just wanted to put my thoughts down. 
- Was thinking the other day, when using your inventory, let’s say eating a sandwhich, you are taken out of your inventory and can not access it again until the animation/progress bar is complete. Would be nice to be able to stay in your pockets, instead of it opening and closing a bunch of times when eating and drinking a few items
- I know the hot bar exists, but especially as a LEO that’s already full, and doesn’t really cover everything as is, do other hot keys exist that I don’t know about? As it stands I would have (when weights are adjusted) my: Taser, pistol, flashlight, sling weapon, baton. I could put the radio in 6, but that’s where I try and keep ammo. 
- I know weapon weights are going to be tough to nail down, shouldn’t be able to keep an armory in your pants, but with 2 weapons and a vest you can’t carry anything else. I know this is probably being looked at but just re-iterating. Maybe weapons locked to certain slots in your inventory tied to weapon type? And any confiscated weapons held in a baggy with no weight, similar to when cash is confiscated. 

No real solutions to these, just wanted to make sure I brought it up.

**Comment by Montana-77** [comment]
Inventory/weight reworked for both civ's and LEO's.... will continue to monitor through open beta
