### ISSUE TITLE
Construction

### ISSUE THREAD

**Issue by lmlRockzlml** [HollywoodHeists/public#170]
This is a question and a possible bug...

With construction, are we allowed to just do part of the job or does it need to be fully completed?

If it should be 100% completed then it may need changing to only end the job upon 100% complete as I was able to end the job early and take the pay for the amount of work I completed which was 55% giving me $5500

**Comment by YouTri** [comment]
I could be wrong but i believe when you start the job it says you can complete early but only get x amount of pay

**Comment by lmlRockzlml** [comment]
ahh fairs, I will continue then :)
