### ISSUE TITLE
Construction Team

### ISSUE THREAD

**Issue by SharKingKong** [HollywoodHeists/public#174]
There is an issue currently with construction teams, earlier on the server I was part of a 4 person group, and I was not the leader. After some time I left the server but as I rejoined a little while later I could not join a different group or start a job, cause I was not the leader of the party.

I think you can only join one party per server restart, or at least that's what i suspect is happening. I tried to change the job at city hall and reselect the Builder job but the result was still the same.

**Comment by lmlRockzlml** [comment]
I kicked you from the group after you left, I couldnt start another job either but Dom could

**Comment by lmlRockzlml** [comment]
I just went to start a construction job and SharKingKong is still in my team even though I kicked him from the team last night. I cant start a job either.

**Comment by lmlRockzlml** [comment]
We sorted it out, we both had to be online to change the team up. maybe make it so it is possible to remove when someone is offline as it could cause issues with headpops too...?

**Comment by Colt-Sterling** [comment]
Thanks for the heads up on this gang! We'll look into it

**Comment by AliAliJr** [comment]
Fixed.
