### ISSUE TITLE
Unconscious State Tuning

### ISSUE THREAD

**Issue by DeliriousHoot** [HollywoodHeists/public#176]
So it seems right now that the Unconscious state is super powerful. I was stabbed today and it only put me into an unconscious state, realistically I should not be able to get back up without EMS coming. I'm not sure about shooting someone but could definitely test this. Unconscious should really only work for getting punched or maybe ejecting.

**Comment by MrKennyG** [comment]
Agreed if it can be changed to non lethal "deaths" go to unconscious state that would be best. Anything like stabs / crowbar / gunshot go to "dead" state.

**Comment by Colt-Sterling** [comment]
Gun shots should already put people in the "dead" state already. But we can look into adding knives (etc.) to the list fs!

**Comment by MrKennyG** [comment]
o ok. Clint went down last night from falling and was able to get into a car but we couldnt get him out cause he bled out inside. He couldnt "wake" back up and when i tried to shoot him and get him into the "dead" state it diidnt work either.

**Comment by AliAliJr** [comment]
Melee weapons added.
