### ISSUE TITLE
Another UCL issue

### ISSUE THREAD

**Issue by YouTri** [HollywoodHeists/public#178]
I don't know if it sold or not but my GTR isnt on the lot and its not in my garages or impound. If it sold i didn't get a payment from the lot. So i essentially got nothing from selling my car. I have no way to tell if it sold or is just lost in time because it didnt get sent to my garage or impound.

**Comment by AliAliJr** [comment]
what's your character name?

**Comment by YouTri** [comment]
Logan Hendrix

**Comment by AliAliJr** [comment]
someone bought your car and the money transferred to your bank account.

**Comment by AliAliJr** [comment]
someone bought your car and the money transferred to your bank account.
from now you will get an email, when you sold your vehicle check
