### ISSUE TITLE
Housing Thoughts and Suggestions 

### ISSUE THREAD

**Issue by DeliriousHoot** [HollywoodHeists/public#18]
General Thoughts: I like the idea behind what is there and I think the Sims like decorating could definitely work with some tweaks to how you interact with furniture.

#1 - Being able to decorate in an MLO while very cool can to some degree be a bit pointless as most of the interior is already decorated leaving little room for actual customization. I could also see this potentially being a performance issue down the line depending on how many homes are MLO based and server size. Hopefully we will be able to when purchasing a house get to choose between a couple blank slate interior layouts (single floor, two floor and variants of those templates)

#2 - Purchasing each piece of furniture. I firmly stand by the belief that decorating shouldn’t cost anything especially when you consider that some people will likely start interior design businesses and from my experience people can get super creative when given free use of all the furniture (there are some crazy designers out there). It also adds on to the purchase of the home. While I understand the idea behind “buying and selling” of the furniture I think in reality it takes away from the experience itself. 

#3 - The way furniture is moved. It took me quite some time to get used to how to interact and move the furniture and even still I don't find myself having the full control I’m used to. The biggest thing I loved about the Nopixel furniture decorating was having an XYZ Axis and handle to move things on. Much like if you’ve ever used an 3D modeling package you get 3 arrows that move or rotate on the XYZ axis which allows for a much smoother experience. I also find it really allows you to be far more precise. Additionally adding the ability to move an object with specific values would be very beneficial (Example by what I mean: I spawn a couch, couch spawns in at coordinates X = 0, Y = 0, Z = 0, I move the couch along the X axis and input the number 46.6, this allows for even more precise movement and means if I need another object at that exact same X value but I want it a Y = 24 it allows me to exactly put the X value at the same number. it is sometimes also needed as certain housing layouts aren’t perfect values)

#4 - Amount of Furniture. I like what is already there but I think overall it’s pretty lacking. I know there are a ton more objects that can be added and used from the regular base GTA. I think to really be able to decorate and make the house your own the amount of furniture pieces really needs to be pushed up and more added because as it stands atm a lot of houses are going to look the same.

Overall I like the thought that was put into the decorating system but I think it actually still has a decent amount more to go before I’d consider it a full system to work with. It’s also a system that can have stuff added to it over time so while it should launch with more furniture then it has in its current state it’s also something that can always be added with. I didn’t notice and bugs while working with the decorating so that’s a big plus.

**Comment by AliAliJr** [comment]
Housing is updated, soon we will drop it to main.
