### ISSUE TITLE
Trucking Crashes

### ISSUE THREAD

**Issue by CaptainWied** [HollywoodHeists/public#181]
Game crashed when doing the trucking job and in the deliver package animation. I attached the crash report if that helps.

[CfxCrashDump_2023_02_09_21_42_55.zip](https://github.com/HollywoodHeists/public/files/10701780/CfxCrashDump_2023_02_09_21_42_55.zip)

**Comment by AliAliJr** [comment]
Fixed. Thanks for reporting.
