### ISSUE TITLE
Construction Site Glitch

### ISSUE THREAD

**Issue by momocitaa** [HollywoodHeists/public#183]
i did a Construction Sit job with all the new added welding spots and the job said i was at 94% when the map showed i was finished. I returned the company car thinking it was only a visual but i got $4,700 instead of the full $8k or whatever the full amount is now.

**Comment by Colt-Sterling** [comment]
The construction job took a slight nerf, the paychecks were too powerful. As for the percentage, I think it's probably because we disabled the part where you have to return the cement truck because people's cars kept getting taken by DOT when they went to return it.

**Comment by ItsTrihawk** [comment]
Colt, idk if this helps, but me and Bo did construction and somehow managed to get 96% so I'm not sure if it has to do with returning the truck or not!

**Comment by Colt-Sterling** [comment]
Interesting. Appreciate the update. I'll see if I can get it figured out.

**Comment by roachy43** [comment]
I have always been able to get 100%, in fact sometimes having walls left to place in when it hits 100%. I only do the one near cat café though, next time I'm in city ill try a different one and see if I get a different result to see if it might be site dependant?

**Comment by AliAliJr** [comment]
Fixed.
