### ISSUE TITLE
Outfit resetting after logging off

### ISSUE THREAD

**Issue by DeliriousHoot** [HollywoodHeists/public#184]
Currently when you log out and log back in your outfit defaults to the last one that you took out of a saved closet or clothing store rack, it would be nice if it would just choose the last outfit you were wearing as there's been a couple times I've logged out at MRPD with my cadet uniform on and logged back in with an outfit that should not be seen at MRPD

**Comment by cvalenta44** [comment]
I'm assuming that you are just changing with the outfit bag. From what I heard from colt "that it's like hologram clothes"
