### ISSUE TITLE
Hunting license

### ISSUE THREAD

**Issue by BigTony7** [HollywoodHeists/public#188]
I don't know if anyone has talked about this but I've bought multiple hunting license because the options switch sides, it's very irritating that I spend all this time hunting just for it to go all to waste because you can still buy a hunting license while owning a hunting license. I don't know if there's something that can be done so you don't buy multiple licenses?

**Comment by AliAliJr** [comment]
sure, we will look into it.

**Comment by AliAliJr** [comment]
![image](https://user-images.githubusercontent.com/86673561/219581165-bd7bc377-e343-4a3c-abba-cc8720452092.png)
Added Cletus for license.
