### ISSUE TITLE
Stress 

### ISSUE THREAD

**Issue by Aroebic** [HollywoodHeists/public#19]
I feel that you get stressed out way to easily and should be reduced a decent amount

**Comment by ItsGabble** [comment]
We have a stress rework on our list. Keep an eye out over the next week or so for that.

**Comment by Montana-77** [comment]
stress nerfed slightly... TONS of options for lowering stress now in stores and also buffed lots of stress relief from different items in the city... but we suggest you smoke Redwoods of course!
