### ISSUE TITLE
Casino Wheel suggestion

### ISSUE THREAD

**Issue by AlfieIsSmart** [HollywoodHeists/public#194]
Hi There,

I'm not sure if it is possible to do this but, I had an idea to maybe add / change a prize to "Cat Cafe Voucher" or burger shot etc on the casino wheel. This could be good to increase more customers to actual person ran food establishments.

Alfie

**Comment by AliAliJr** [comment]
Gift cards added to casino wheel, thanks for your suggestion.
![image](https://user-images.githubusercontent.com/86673561/230759765-b4978d4b-3f16-4765-b37b-d369e02df48b.png)
