### ISSUE TITLE
car parts and respray not staying.

### ISSUE THREAD

**Issue by roachy43** [HollywoodHeists/public#198]
so this has happened to me 4 separate times with a couple of different vehicles but after getting some work done and a respray and then picking my vehicle back up whether thats from impound or a garage. the parts and paint have been different. This has been with parts installed from ottos or just the normal shop next to pdm. i just took my everon out of impound and it is bright orange and has like half the parts on it that were previously installed.

**Comment by AliAliJr** [comment]
Should be good now.
