### ISSUE TITLE
Repair kits and vehicle storage

### ISSUE THREAD

**Issue by Mi11er1** [HollywoodHeists/public#20]
I assume these things have been talked about but was wondering if vehicle repair kits will get added. Mechanics arent always around and when it breaks down you have to leave it where it died. 

I believe the car truck weight limit has been talked about but wanted to add it just to see if that was planned change for full release. Have to leave oxy packages on the ground if you get more than 3 per run.

**Comment by Montana-77** [comment]
Repair kits buffed to bring cars to much better state without mechanics... also all vehicle trunk values have been reworked/buffed.
