### ISSUE TITLE
Number of Participants in a kidnapping

### ISSUE THREAD

**Issue by momocitaa** [HollywoodHeists/public#202]
So we have a pretty big story line planned up for the kidnapping of a Government Official. The plan is to take place AFTER the Race happening on March 24. We are assuming there will be ALOT of people on and especially gov'n officials. The rule is "Heist, Robberies, Drug sales, Kidnapping, Car boosting will be limited to 4 members at a time. This will mirror the same rules for civilians not in gangs." But in this case we would like to have at least 8 people participating in the kidnapping.  Because 4 v like almost 20 cops isnt fair cuz this will spark every cop to be on our butts. so we would like to have 8 participants for this specific event since All 8 have a story with this specific Gov'n Official and would make for a fun time for everyone imo. So if there can be a consideration for this specific event that would be great!

**Comment by Pigglesworrth** [comment]
Just my peasant 2 cents. I feel like this brings up future problems in why should they allow 8 now only for you guys?, I feel like it seems a little unfair to others if you guys get allowed to have 8 and everybody else gets stuck on 4.

**Comment by momocitaa** [comment]
Im not saying its ONLY for us but more for the situation we're in. In the future if someone else wanted to do an event such as this if they were to put in the same effort to plan like us and communicate with the higher up who says they cant! i think its all communication. The limit is 4 for the average person. like if 4 of us decided to kidnap Louie its not needed to have alot more protection since youre an average person in town. In this case we are doing a Government Official who has the backup of a billion officers. Even then if someone wanted to have 8 people to kidnap 1 person they can also make the argument as to why they think they need that many and so on. No one is saying this is only a one time event, it can be multiple events inthe future as along as its communicated with all involved. :3

**Comment by Pigglesworrth** [comment]
Fair but you def would need 20 people to capture Louie, He is a high class target, top of the line, best criminal mastermind Reformed short king etc etc.

**Comment by momocitaa** [comment]
right...

**Comment by Stetty78** [comment]
The limitation of 4 if for the actual kidnapping activity that is accessed through the local in city. Kidnapping for a story arc is different and I don’t see any issue with y’all having 8 people involved.

**Comment by Bergsbrew** [comment]
Lets talk about this in a ticket.

**Comment by momocitaa** [comment]
wait is that not what this is O.o
