### ISSUE TITLE
Add Cars Speed Limiter and better cruise control 

### ISSUE THREAD

**Issue by LittleDigz** [HollywoodHeists/public#207]
In the city there is a cruise control but it when your turn to hard the cruise turns off. Also would be amazing for a speed limiter in the cars.

**Comment by cvalenta44** [comment]
.

**Comment by Colt-Sterling** [comment]
The team can look into better cruise control scripts no problem! As for a speed limiter, we actually already have one in the city, it's set to 160, but some cars have engines that can blast past the limiter. It still slows them down a fair bit, but they're just too powerful currently. Will be fixing this as the city grows.

**Comment by AliAliJr** [comment]
cruise control wont turn off, on hard turns now.
