### ISSUE TITLE
Helicopter Issue

### ISSUE THREAD

**Issue by Midori33** [HollywoodHeists/public#208]
so i think you can get ejected from helicopters like you do with cars. even if you just slightly graze something. and i think if you do get ejected and get downed you get incredibly scuffed. Like downed but can still use phone and speak. also wasnt able to check in to pillbox. not sure how to solve this but i figured i would report it.

**Comment by ChugThis** [comment]
Thanks for the report, I’ve noticed this as well. Don’t hit anything in a Heli!

**Comment by Colt-Sterling** [comment]
Noted. Thanks for the heads up! I'll go pour a whole bottle of glue in the seat. May even add more harnesses while we're at it.

**Comment by AliAliJr** [comment]
We tested this and were unable to achieve the same results. It shouldn't happen again, but if it does, let us know.
