### ISSUE TITLE
New hair

### ISSUE THREAD

**Issue by QuintenM911** [HollywoodHeists/public#209]
Can no longer wear a hat with this hair style after new additions it was two numbers 57 and 27 both don't work with the hat
![Hat-hair](https://user-images.githubusercontent.com/90533639/228377776-aae70a42-34de-4883-9541-c8e4a3c26f0d.png)

**Comment by DeliriousHoot** [comment]
can confirm all hairs are broken currently with hats

**Comment by AliAliJr** [comment]
Fixed.
