### ISSUE TITLE
Goldbar/Diamonds - Not Mining -

### ISSUE THREAD

**Issue by Doniqq** [HollywoodHeists/public#211]
Currently there doesn't seem to be a place to take gold bars obtained from melting down at the pawn shop and diamonds also melted down from diamond rings or found while diving. 
The guy that buys that stuff from mining does not want them and I have noticed that the gold bar and diamonds from the mining job look completely different.

**Comment by cvalenta44** [comment]
I've noticed that the diamonds aren't fixed but the gold bars are able to be sold now

**Comment by Colt-Sterling** [comment]
We will get the diamonds fixed and added as well.

**Comment by AliAliJr** [comment]
Added.
