### ISSUE TITLE
Purchasing a Car

### ISSUE THREAD

**Issue by AlfieIsSmart** [HollywoodHeists/public#216]
I think it would be a great idea for there to be a "Are you sure you want to purchase this vehicle" option after clicking buy vehicle, in case of any mis-clicks. Just to be safe

**Comment by LittleDigz** [comment]
THIS WOULD BE AMZAING!!!!!!!!!!!!!!! :( Yes I am a victim of miss clicking

**Comment by Meelokbruvv** [comment]
Are you referring to the dealerships or used car lot cause I believe used car lot has that.

**Comment by cvalenta44** [comment]
At PDM and the premium car dealership they don't have a confirm to buy, you click buy vehicle and then you have bought the vehicle.

**Comment by Colt-Sterling** [comment]
I think by now, we've all bought a car we don't want LOL. We're going to implement a confirmation prompt that pops up before you buy a car. So we can all save our money and spend it where it matters. On Redwood cigarettes.

**Comment by AliAliJr** [comment]
Added.
