### ISSUE TITLE
Issi Sport Dissappeared!

### ISSUE THREAD

**Issue by KorieJoe** [HollywoodHeists/public#219]
I tried to take my Issi Sport out of pill box garage in which it spawned a different color & claimed not to be my car. I tried to gain entry through picking the lock to see if I could put in back in storage but again didn't register as my car. When I tried to peek back at my car list in storage its no longer listed there either. Help!

**Comment by Colt-Sterling** [comment]
Oh no! We can fix this, no worries!

**Comment by Colt-Sterling** [comment]
Have you checked your garage app to make sure it didn't get sent to impound?

**Comment by KorieJoe** [comment]
I will check now, good idea!

**Comment by KorieJoe** [comment]
No cars in impound

**Comment by Colt-Sterling** [comment]
All good, we will check it out

**Comment by KorieJoe** [comment]
Thank you! Sorry for the trouble.

**Comment by Colt-Sterling** [comment]
No worries and no trouble 😎 I'll let you know when we get it fixed

**Comment by Colt-Sterling** [comment]
Can you come check again at Pillbox garage when you get a chance?

**Comment by KorieJoe** [comment]
Sorry just saw, its here! TY for fixing it!

**Comment by Colt-Sterling** [comment]
No problem!
