### ISSUE TITLE
Treasure Hunting Issue

### ISSUE THREAD

**Issue by Midori33** [HollywoodHeists/public#220]
So treasure hunting may be too difficult now. So I got pretty lucky on my first clue in that it was on the top of a mountain so there wasnt a whole lot of area i had to look but the second clue was on flat ground and i spent at least 30mins walking around 3rd eyeing trying to find it and saw nothing. The first one seemed to be basically a speck on the ground. im thinking that either the area in which the items start burning should be decreased or the size of the hit box for 3rd eyeing should increase if possible.

**Comment by ItsLoftus** [comment]
Yeah ive spent 4 hours walking around the same place 3rd eyeing everything and nothing

**Comment by AliAliJr** [comment]
The area of the third eye is increased.
