### ISSUE TITLE
Exotic Dealership Bug

### ISSUE THREAD

**Issue by Meelokbruvv** [HollywoodHeists/public#221]
![image](https://user-images.githubusercontent.com/104778184/230749238-1a29f96f-3398-432b-bf29-25cc9892eb8f.png)

I believe the Bugatti divo is scuffed the pad I'm currently looking at is not a divo so it scuffed the third eye and you and if you look in the distance their is a Bugatti Chiron inside the bugatti divo

**Comment by AliAliJr** [comment]
We tested this and were unable to achieve the same results. It shouldn't happen again, but if it does, let us know.
