### ISSUE TITLE
Grave Digging LEO Requirement Thoughts

### ISSUE THREAD

**Issue by MrKyRy** [HollywoodHeists/public#223]
So I know this will not be a very likable idea but I personally believe grave digging should notify LEOs. Digging up graves is obviously illegal and it will add a form of interaction with people. It seems grave digging is just grinding for items and you can get a large array of items which I think should have some risk / reward to it. Even though there is not dirty money involved, I believe it should be considered a crime and LEOs should be notified. It also forces grave diggers to come up with unique interactions and stories. 

Thoughts?

**Comment by xxtraspicyy** [comment]
this has been discussed briefly and the small consensus is that notifications are not necessary, you can patrol past the cemetery or even in the cemetery etc as grave digging is illegal and go from there

**Comment by Midori33** [comment]
maybe if they do it in the day but if youre grave digging at night then there should be little to no notifications.

**Comment by ItsLoftus** [comment]
I'd be fine with it notifying LEO's, just hope it doesn't require them. Its really 1 of the few things we can do without the police around

**Comment by AliAliJr** [comment]
Random alerts added, also F1 > check status to see if target has grave dirt on his clothes.
