### ISSUE TITLE
Melted Gold Weight

### ISSUE THREAD

**Issue by momocitaa** [HollywoodHeists/public#225]
so i noticed there has been weight added to gold! nice but i found a small issue. so 1 bar is 7 pounds and i had melted 15 bars worth which is 105  pounds. so if i were to have gone surpassed my 120 carry limit how would i pick up my thing  out of the pawn shop? There should be a way to take it out my quantity if it were to happen to someone.

**Comment by AliAliJr** [comment]
Thanks for reporting, changed to 1 pound each.
