### ISSUE TITLE
Heists 

### ISSUE THREAD

**Issue by YouTri** [HollywoodHeists/public#23]
**These are some of the notes that I have seen from my testing and completion of all heists as seen on this list.** 

Yacht Heist-  (So for starters you can bug out all the AI's that spawn in by flying a helicopter over instead of taking the boat which allows you to immediately board without having to clear the boat. You can also still continue to collect Items after bugging out the AI's. Also be aware there are certain areas where it will prompt you to grab a stack will cause you to fall through the map and put you at 577 which then prompts you to take all the items you collected to the buyers. The artifacts are currently also bugged where they are completely invisible and also cause you to fall through the map. Payout overall varies you can grab stacks of cash on the yacht that will give you $60,000 that you keep after talking to the buyers, while item turn-ins average around 3500-4500 marked cash.)- All happens when you fly a helicopter to the Yacht Heist instead of taking a boat.

 When starting the Yacht Heist normally with a boat the AI's that attempt to fight you as you board the boat are properly spawned and you must clear them out while moving room to room. Artifacts and other items you must grab are now visible and allow you to collect them without falling through the map. Once all items have been secured you leave the boat and are prompted to meetup with the buyers once again. The payout is the same as what happens with the helicopter attempt. The money stacks you grab off the boat gives you about $60,000 in marked cash that you keep after talking to the buyers instead of them taking it and giving you a smaller cut. You are also given an additional 2500-4500 in marked cash from all of the artifacts that you had grabbed and handed over. Think personally we should get a fraction of the 60k not the entirety and then we should get a random
amount per artifact that you hand over.

Fleeca banks- Overall currently fleecas can be seen as not worth it, the setup alone you can expect to spend $3000 on the setup which includes 3 drills and a bag just to grab the items in the vault with a total payout of 4500 in marked cash. Also that 3k doesn't include the hacking device or bank card you would need to get ahead of time to make it into the back section of the bank. After the first door you can crack a safe that gives you a "chance" at getting a bankcard from the safe. The reason I say "chance" is because after 2 fleecas we have cracked the safe both times and has given us the bank card to get into the back both times I feel as if more testing should be done to see if it does guarantee that you get the bank card or if we were just lucky enough to secure it both times. After everything is said and done you are once again prompted to go meetup with buyers for everything that you took from the fleeca only to receive about 4500 in marked cash which barely covers the cost of the setup let alone if you have to split that with someone else. On top of that you would have to favor the profit you would make vs. the time you would spend in jail and the fines you would face if you were caught in the chase.

Vangelico's payout is okay maybe a slight boost. We did it and got $20,000 maybe a bump to $25,000. I think the weapon tier should be lowered. As of now AKs, and a Combat Pistol were eligible to hit the cases.  I think if there is an UZI, Mini-Uzi or any other 2 Handed weapon should be eligible. AKs are gonna be hard to get with the LEO requirements alone. Along with the PVP Aspect of the island. If there is gonna be a black market within San Andreas and not just the island. SMGs should be sold and useable for the Vangelico.

Oil Rig. Oil Rig is essentially useless. You Need AKs and Body Armor and you still barely make it on the oil rig alive. With the AI being absolutely cracked.  You need a Hacking USB which isn't easy to get at all. Not only do you need AKs, Body Armor, and a Hacking USB you get payed out in materials. It isn't worth it for materials alone. Let alone the amount you get is terrible. Why do all this work and risk a ton of items when I can go to the recycling place and get the same amount without a chance of dying. If you search the crates before completing the Hack you don't get anything out of the crates. Can be fixed by either Not allowing a 3rd eye option until hack completion or When trying to search it says you must complete the hack.

**Comment by Stagonium** [comment]
Going to be transitioning these into a separate post for each heist for organization sake, thank you for this!
