### ISSUE TITLE
Fleeca Notes & Issues

### ISSUE THREAD

**Issue by ItsGabble** [HollywoodHeists/public#24]
"Fleeca banks- Overall currently fleecas can be seen as not worth it, the setup alone you can expect to spend $3000 on the setup which includes 3 drills and a bag just to grab the items in the vault with a total payout of 4500 in marked cash. Also that 3k doesn't include the hacking device or bank card you would need to get ahead of time to make it into the back section of the bank. After the first door you can crack a safe that gives you a "chance" at getting a bankcard from the safe. The reason I say "chance" is because after 2 fleecas we have cracked the safe both times and has given us the bank card to get into the back both times I feel as if more testing should be done to see if it does guarantee that you get the bank card or if we were just lucky enough to secure it both times. After everything is said and done you are once again prompted to go meetup with buyers for everything that you took from the fleeca only to receive about 4500 in marked cash which barely covers the cost of the setup let alone if you have to split that with someone else. On top of that you would have to favor the profit you would make vs. the time you would spend in jail and the fines you would face if you were caught in the chase." - Tony

**Comment by Montana-77** [comment]
Fleeca was also a part of the complete rework of heists/heist rewards... Took many things you all posted into consideration. Thank you for all the testing!
