### ISSUE TITLE
Vangelicos Notes & Issues

### ISSUE THREAD

**Issue by ItsGabble** [HollywoodHeists/public#25]
"Vangelico's payout is okay maybe a slight boost. We did it and got $20,000 maybe a bump to $25,000. I think the weapon tier should be lowered. As of now AKs, and a Combat Pistol were eligible to hit the cases. I think if there is an UZI, Mini-Uzi or any other 2 Handed weapon should be eligible. AKs are gonna be hard to get with the LEO requirements alone. Along with the PVP Aspect of the island. If there is gonna be a black market within San Andreas and not just the island. SMGs should be sold and useable for the Vangelico." -Tony

**Comment by Montana-77** [comment]
Rewards reworked, also allowing more weapons to be used in the breaking of cases... to make easier access of doing the heist..
