### ISSUE TITLE
Oil Rig Heists Notes & Issues

### ISSUE THREAD

**Issue by ItsGabble** [HollywoodHeists/public#26]
"Oil Rig. Oil Rig is essentially useless. You Need AKs and Body Armor and you still barely make it on the oil rig alive. With the AI being absolutely cracked. You need a Hacking USB which isn't easy to get at all. Not only do you need AKs, Body Armor, and a Hacking USB you get payed out in materials. It isn't worth it for materials alone. Let alone the amount you get is terrible. Why do all this work and risk a ton of items when I can go to the recycling place and get the same amount without a chance of dying. If you search the crates before completing the Hack you don't get anything out of the crates. Can be fixed by either Not allowing a 3rd eye option until hack completion or When trying to search it says you must complete the hack." -Tony

**Comment by Montana-77** [comment]
SLight nerf to oil rig AI's... all heist payouts changed
