### ISSUE TITLE
Yacht Heist Notes and Issues

### ISSUE THREAD

**Issue by Stagonium** [HollywoodHeists/public#27]
"Yacht Heist- (So for starters you can bug out all the AI's that spawn in by flying a helicopter over instead of taking the boat which allows you to immediately board without having to clear the boat. You can also still continue to collect Items after bugging out the AI's. Also be aware there are certain areas where it will prompt you to grab a stack will cause you to fall through the map and put you at 577 which then prompts you to take all the items you collected to the buyers. The artifacts are currently also bugged where they are completely invisible and also cause you to fall through the map. Payout overall varies you can grab stacks of cash on the yacht that will give you $60,000 that you keep after talking to the buyers, while item turn-ins average around 3500-4500 marked cash.)- All happens when you fly a helicopter to the Yacht Heist instead of taking a boat.

When starting the Yacht Heist normally with a boat the AI's that attempt to fight you as you board the boat are properly spawned and you must clear them out while moving room to room. Artifacts and other items you must grab are now visible and allow you to collect them without falling through the map. Once all items have been secured you leave the boat and are prompted to meetup with the buyers once again. The payout is the same as what happens with the helicopter attempt. The money stacks you grab off the boat gives you about $60,000 in marked cash that you keep after talking to the buyers instead of them taking it and giving you a smaller cut. You are also given an additional 2500-4500 in marked cash from all of the artifacts that you had grabbed and handed over. Think personally we should get a fraction of the 60k not the entirety and then we should get a random
amount per artifact that you hand over." - [Transferred from parent post](https://github.com/HollywoodHeists/public/issues/23)

**Comment by Montana-77** [comment]
complete rework of yacht heist and rewards..  Bugs patched :)
