### ISSUE TITLE
Robberies

### ISSUE THREAD

**Issue by Malakill3r** [HollywoodHeists/public#28]
House Robberies- House Robberies have some minor issues that happen to occur first of which being the way pings are sent immediately to LEO's. As soon as you start to use the lockpick on a door at one of the robbable houses Leos are immediately alerted weather you are sneaking around or running while picking the lock, there is no way as a Crim to prevent the ping from being sent to the police even if noone is around to witness you breaking into the house. The other issue being that we have not seen houses that you are able to break into reset until a tsunami has happened, not entirely sure if that is the intended effect or not but feel as if it doesnt reset periodically without a tsunami many individuals will not be able to partake in such an activity. One final issue being that on some of the houses you exit if there is an overhang above the door you will spawn ontop of that overhang instead of directly outside of the door once again just a minor issue but feel as if it should be brought up.

 Store Robberies-Only some minor issues with store robberies the primary one being that with stores that have two hittable cash registers is that half of the time the store clerk blocks the second register from being hit. I dont know if there would be a way to move all the clerks slightly closer to the counter to allow people to move behind him to reach the second register is possible but feel as if it would be the easiest way to fit that issue. The other inconvenience would be the RNG on getting the sticky notes to the safes in the back of many stores. We have hit somewhere in the ball park of 45-50 store robberies and out of all of these times we have only seen the sticky note be given to us once or twice. Once again not a huge issue on this one but could be fixed with a slight bump to the RNG scale.

**Comment by Stagonium** [comment]
Going to be transitioning these into a separate post for each heist for organization sake, thank you for this!
