### ISSUE TITLE
Drugs

### ISSUE THREAD

**Issue by YouTri** [HollywoodHeists/public#29]
These are my notes from what i have seen involving drug aspects.

Weed- Weed allowed me to sell from $6-$200 definitely needs an improvement
Cocaine- Cocaine sells for $400 is good if there is other forms of sale (view suggestion)
Meth- Meth sold for $120-$200. Needs improvement (view suggestion)
Crack-N/A. 

Getting a ping every corner sell is a bit excessive. We have went from South LS i.e Grove, Forum, Carson.  Back Alleys on Winewood, The Beach and even in the County. 

$400 Dollars isnt worth a chase, fines, and jail time. 

A suggestion to help the ping issue.

Add Drug Trafficking- Drug Trafficking would require a set amount of Cocaine/Meth. It auto pings LEO once the car starts driving. The payout is much higher but much more risky. This would be able to make corner selling an option for the extra amount of drugs left over. If not, Meth needs a pay improvement and pings need to be less.

**Comment by ChugThis** [comment]
Work on drugs would be appreciated. Needs a good balance of actual ability to sell drugs and make money, but a correct amount of risk. Being able to sell anywhere at all is useful for crims for sure. And I believe the point is not to sit and sell and sell and sell but rather be forced to move around a little. That being said, even with 2 people selling a few items in one spot, I got 10+ pings and map markers; which completely took over my ability to respond to anything else as the MDT got overrun with those pings and calls. I can’t imagine a city full of people selling. Seems like it’s going to end up being free money the way it’s set up as we will have an overwhelming amount of calls to respond to, so by the time you’re actually able to catch someone and handle that few hundred dollar crime, thousands of dollars will be getting sold all over the map

**Comment by Montana-77** [comment]
Pings for LEO's brought down.. Drug sales balanced to further match the economy.. Specific Drug sell locations added as well... Thank you for the feedback!
