### ISSUE TITLE
House Robberies Notes & Issues

### ISSUE THREAD

**Issue by ItsGabble** [HollywoodHeists/public#30]
"House Robberies- House Robberies have some minor issues that happen to occur first of which being the way pings are sent immediately to LEO's. As soon as you start to use the lockpick on a door at one of the robbable houses Leos are immediately alerted weather you are sneaking around or running while picking the lock, there is no way as a Crim to prevent the ping from being sent to the police even if noone is around to witness you breaking into the house. The other issue being that we have not seen houses that you are able to break into reset until a tsunami has happened, not entirely sure if that is the intended effect or not but feel as if it doesnt reset periodically without a tsunami many individuals will not be able to partake in such an activity. One final issue being that on some of the houses you exit if there is an overhang above the door you will spawn ontop of that overhang instead of directly outside of the door once again just a minor issue but feel as if it should be brought up." -JFK

**Comment by Montana-77** [comment]
Complete house robbery rework... will be pushed to main very soon..
