### ISSUE TITLE
Store Robberies Issues & Notes

### ISSUE THREAD

**Issue by Stagonium** [HollywoodHeists/public#31]
"Store Robberies-Only some minor issues with store robberies the primary one being that with stores that have two hittable cash registers is that half of the time the store clerk blocks the second register from being hit. I dont know if there would be a way to move all the clerks slightly closer to the counter to allow people to move behind him to reach the second register is possible but feel as if it would be the easiest way to fit that issue. The other inconvenience would be the RNG on getting the sticky notes to the safes in the back of many stores. We have hit somewhere in the ball park of 45-50 store robberies and out of all of these times we have only seen the sticky note be given to us once or twice. Once again not a huge issue on this one but could be fixed with a slight bump to the RNG scale." - [Transferred from parent post](https://github.com/HollywoodHeists/public/issues/28)

**Comment by Montana-77** [comment]
Clerks adjusted to be closer to counter ... will monitor further
