### ISSUE TITLE
Car Boosting

### ISSUE THREAD

**Issue by Malakill3r** [HollywoodHeists/public#32]
As some have seen boosting may need a bit of work to make it to a point of where it can actually become worth wile to everyone. The initial issue being the very first boost everyone needs to work through and that is the D class, from what we have seen so far is that some of the vehicles do not reach speeds that could be capable of evading many police officers. I understand that these are the bottom of the barrel vehicles and they should not be able to outrun LEO's on straightaways but there needs to be a middle ground on at least having a chance of escaping. The other issue being the hacks that the passenger needs to get through on such a low class vehicle seem to be entirely to extensive. On one D class boost alone we had to hit 12-13 hacks in a row before we were even able to disable the tracker on the car and that is not including how difficult some of the hacks are to even do. One way I could see this being prevented is by adjusting the amount of hacks are needed to disable a tracker per class of boost( ex. D class-5 Hacks C class-7 hacks B class- 9 hacks A class- 11 hacks S class- 13 hacks). I also feel like the intensity of the hacks should also coincide with the class of the boost. By that I mean that for a D class, individuals should not have to deal with a Braille hack so early on into the entire leveling system. Once again these are just suggestions on if they are possible to fix overall enjoy the Idea just find it hard to be enjoyable with such situations so early on.

**Comment by iTzaDeAdHoBo** [comment]
also cars have had an issue where they come almost empty on gas, i think just for boosts specifically the gas consumption could be a little longer before they run out and should coincide with the tier as well being super cars run out of gas a little quicker lower class cars take a little longer

**Comment by MrKennyG** [comment]
This is already all in the works. Spoke to the boss man. A lot of changes coming to boosting!!! :D

**Comment by Montana-77** [comment]
Tons of changes to boosting. implemented a lot of the one's you guys mentioned... gas is still random though. The best boosters take a jerry can!   Thank you for the feedback!
