### ISSUE TITLE
CARS CARS CARS

### ISSUE THREAD

**Issue by MrKennyG** [HollywoodHeists/public#35]
Hello Government, 

I think it would be smart to lock all cars to a certain speed ( 140mph ) could be a good start! This makes it so no matter what cars get imported / tuned...ect no car will ever be able to go past this certain MPH lock. This balances most super cars / good high quality cars in a top speed category right at the start of the city. Once all cars are locked to a top speed you can focus on handling / acceleration / brakes.. ect of cars and bikes to have advantages over others.  Stops people from abusing certain vehicles just for topspeed and "highway blasting" Also keeps things fair for both parties crims and cops.

**Comment by Stagonium** [comment]
The global speed limiter was implemented and is in a testing phase currently.
