### ISSUE TITLE
Phone Bug After Reset 

### ISSUE THREAD

**Issue by MrKyRy** [HollywoodHeists/public#39]
After the reset I believe there is an issue with the phones. When I try to download an app, I previously had on the phone (Yellow pages) it tells me it is already on my phone but there are no downloadable apps on my phone. Only the default. The only fix I have seen is to uninstall the app from the app store and redownload it. Not a super big deal but wanted to make it known.

**Comment by Montana-77** [comment]
Delete apps twice unfortunately, we made it known to the provider of the phone script.
