### ISSUE TITLE
Racing App. 

### ISSUE THREAD

**Issue by Jumbi03** [HollywoodHeists/public#42]
I am unable to create my own races because I "do not have permission" according to the in app permissions. I'm not sure what permissions that is tied to but wondering if I can get that ability.

**Comment by Stagonium** [comment]
Looks like this may be currently locked behind admin permissions for testing, will update when I get an answer on this.

**Comment by Montana-77** [comment]
There will be announcement on this, but race creation will go to the in city race crews and they will have a member dedicated to creating races.
