### ISSUE TITLE
Fully Repairing a Car without mechanics

### ISSUE THREAD

**Issue by DeliriousHoot** [HollywoodHeists/public#44]
It would be nice if there was some way to fully repair a vehicle when there are absolutely no mechanics around. Currently it seems as though you can only repair the Engine and Body to full when mechanics are not around however that does not prevent the car from locking up as the other parts aren't being repaired. There are definitely going to be times when there are no mechanics around and having the ability to fix your vehicle fully would be very helpful otherwise people's cars are going to get locked up and unusable till whenever a mechanic comes around.

**Comment by AliAliJr** [comment]
issue was fixed. forgot to close this.
