### ISSUE TITLE
Vehicle Imports

### ISSUE THREAD

**Issue by MrKennyG** [HollywoodHeists/public#47]
Everyone loves car imports but i think the server should take a different approach to adding them in. It looks like as of now the imports just replace city cars.. this kinda sucks for a few reasons. Some people might want to buy the city cars and when boosting i had a Sultan RS contract for S+ but it was a scuffed Nissan Skyline instead. This leads to scratching imports which isnt the worst (could lead to issues) but the contracts dont match the car and it can just be a little weird. I have no idea how vehicles get added by not replacing cars that exists but if there is a way it would prolly be the better approach. Could also filted them into there own category at PDM or move the imports completely to new location like the Car Sale place by hayes autobody.

**Comment by Montana-77** [comment]
95 percent of our cars are "add-ons" VERY few replacements (less than 10). Most all vanilla cars are still here. Sultan RS was removed from boosting and tons of other boosting cars were changed up as well.   PDM is in a rework, within first couple weeks of launch expect to see new organization for both vanilla cars and imports.
