### ISSUE TITLE
Jerry Cans

### ISSUE THREAD

**Issue by MrKennyG** [HollywoodHeists/public#48]
AM I AN IDIOT OR ARE THESE THE MOST IMPOSSIBLE THINGS TO USE? Ok.. real talk i somehow got one to work but not sure how that happened... tried to help a friend and we both couldnt get his to work on his car. 

Also is there a way to just pour gas on the ground? When i tried to pour it just scuffed out shaking a lot until i stopped trying to pour.

**Comment by ItsGabble** [comment]
what car model was it, if you know?

**Comment by MrKennyG** [comment]
Both the r34

**Comment by Montana-77** [comment]
I've had same problem with R34... tryt to get in and out of car if it doesn't work, fixed it for me.. also we are removing the need for "cash" to fill up with Jerry can

**Comment by MrKennyG** [comment]
Ok awesome will continue to test other cars and see if any issues appear
