### ISSUE TITLE
Phones

### ISSUE THREAD

**Issue by xxtraspicyy** [HollywoodHeists/public#50]
I think the phones need a bit of a rework, they are so buggy and although you know realistic they don't need to have so many attributes to be usable, I can no longer swipe down to bring the menu up for airdrop etc, my messages have been deleted, the apps are also buggy  if that hasn't been mentioned before. I know a lot of people have had and still have the no signal issue when  charging or after charging (using power bank). 
Understandably not a pressing matter but something to think about if possible.

**Comment by Montana-77** [comment]
Complete phone update... batteries buffed and many things optimized.. will continue to monitor
