### ISSUE TITLE
Del Perro Pier games

### ISSUE THREAD

**Issue by RockemRobotics** [HollywoodHeists/public#51]
First off - SUPER STOKED to see these added in. I just wanted to give some initial notes, while also admitting that these may be things you're already working to fix.

Bang-a-Beaver stops showing red and green beavers after like 100 or 150 points, so a lot of the challenge goes away at that point. I also got a freeze at one point where the hammer was locked and I couldn't do anything but watch the timer run down, but I couldn't repeat it so ¯\_(ツ)_/¯

Nazar Speaks costs $1000 just to have the machine say some words to me? At least with Bang-a-Beaver I'm paying $1000 to play a game and get a high score.

Kitty Claw lets you play as much as you want for only $1000, whether you win or lose, as long as you don't walk away from the machine. You do have to press backspace to leave, which isn't indicated anywhere.

Basket Throw is free, which is a nice change from all of the $1000 games.

The booths have an interaction circle, but unlike every other spot in the city that has an E interaction this one shows no indication that E is the key you need to press to make anything happen. The prices for the food ($1500) seem a bit high too.

The rides cost $3 or $5? That's a _steal_ compared to everything else at the pier.

**Comment by RockemRobotics** [comment]
As a suggestion, could the rides at Del Perro Pier do something to reduce stress?

**Comment by Montana-77** [comment]
All prices brought down... Stress relief to come in the future
