### ISSUE TITLE
Fly-in Locations

### ISSUE THREAD

**Issue by RockemRobotics** [HollywoodHeists/public#52]
Aside from "Last Location" there are four choices for where to fly in when you load into the city each time. Two of them are within two blocks of one another (Police Department and Legion Square) and a third is just up the road from those two (Motel). See the map I attached to see just how close together everything is aside from Paleto Bay.

![LosSantosMapStartLocations](https://user-images.githubusercontent.com/14297779/210161587-1b7795ec-cc57-461d-b46b-5821c31c9f2c.jpeg)

It would be a very nice change if the fly-in locations were more spread out. If we want to keep four locations, why not have this list:
- Paleto Bay (keep it the same)
- Legion Square (keep it the same, no need to also have one right by Mission Row PD)
- Vespucci Blvd (by the shops)
- West Vinewood (maybe in the courtyard of the apartment building at 536, similar to how the current Motel spawn location puts you in the middle of that building)
- [Optional] Sandy Shores, for additional variety and to really spread out spawn locations

![LosSantosMapSuggestions](https://user-images.githubusercontent.com/14297779/210161819-2d412e63-dfe8-4622-82e2-a66437e04d9a.jpeg)

**Comment by Montana-77** [comment]
Leaving everything close to the city for now.. we will come back to this as populations grow in the coming weeks.
