### ISSUE TITLE
Hot dog stand gets stuck

### ISSUE THREAD

**Issue by KosimaGhost** [HollywoodHeists/public#57]
The hot dog stands randomly get stuck when you try to move trhem, and then get you stuck as well. You start not being able to move at all.
You also do not get your deposit back obviously. Here'es a [clip](https://medal.tv/games/gta-v/clips/OQzBNqfoWlfIl/d1337NjfwDqW?invite=cr-MSxyMkIsMjc3NjEzMTIs)to show it.

**Comment by xxtraspicyy** [comment]
i'm just trying to sell some wieners man

**Comment by KosimaGhost** [comment]
UPDATE - After a little bit of troubleshooting with the weiners, I found that you only get stuck if you grab the stall as your selling is turned on. Turn selling off in F1 menu first and you'll be able to move it and let it go without issues. But if not, you'll get stuck on the stall.
