### ISSUE TITLE
Trashmasters Buff

### ISSUE THREAD

**Issue by Midori33** [HollywoodHeists/public#60]
So, I think the trashmasters may need a fuel efficiency and possibly a durability buff because it seems to take multiple tanks of gas just complete one run; They also seem to take decent amounts of damage from even slight scrapes and bumps.

**Comment by Colt-Sterling** [comment]
Appreciate the heads up! We'll look into it.

**Comment by ItsGabble** [comment]
resolved. thanks for reporting!
