### ISSUE TITLE
Minor bug with fishing

### ISSUE THREAD

**Issue by RockemRobotics** [HollywoodHeists/public#67]
![image](https://user-images.githubusercontent.com/14297779/210478928-b347e698-c209-4d20-98ea-7e663b216ddb.png)

I can't figure out how to replicate the issue completely, but even when I successfully catch fish with my rod I get a pop-up telling me I have failed. I think it's related to the fact that if you fail the quicktime event game there is no notification telling you that you've failed then, you only get notifications if you succeed.

**Comment by AliAliJr** [comment]
Fixed.
