### ISSUE TITLE
Weazel News Network whitelisted job ideas:

### ISSUE THREAD

**Issue by Arvardos** [HollywoodHeists/public#68]
Just some ideas I had for a whitelisted Weazel News Network (WNN) reporter job

Rank structure:
Newsie
Reporter
Senior Reporter
Editor

Mandatory training period of 3 weeks for Newsie rank, where they need to accompany a Reporter or higher as often as possible. They can then be assessed by a Senior Reporter or Editor before being promoted to Reporter position.
Reporters must be assessed by a Senior Reporter or Editor before being promoted to Senior, and only if they have shown dedication to the job and creative flair in their reporting duties.
Reporters can be put forward for pilot training by the request of Senior Reporters to an Editor, however only Senior Reporters or above can have the ability to requisition a WNN helicopter.
Two reporters are required to operate a WNN helicopter – a pilot and a camera operator, one of which must be the Senior who requisitioned the helicopter unless directed by an Editor.

Vehicles available:
Newsies have access to a WNN van, and a bicycle.
Reporters have access to an WNN SUV, plus the above vehicles.
Senior Reporters have access to a WNN helicopter, plus the above vehicles.
Editors have access to all WNN vehicles.

Duties and responsibilities:
Accessing an MDT-style tablet, Newsies and above can look for a job where they can go to a determined location and take a photo, which they can then caption and post from the MDT to the News app.
When an LEO attaches to a crime such as a robbery, a ping is sent to Reporters or above notifying them of the location in which they can attach themselves to go on location and get photos/quotes from LEO for the News. Reporters and above are authorized to report on any city council meetings.
Senior Reporters and above can submit requests to have a billboard rebranded for a specific amount of time, meaning other businesses and city departments can pay to have advertising done.
Editors are responsible for tracking the training of all positions in the WNN, along with working to improve the quality of reporting that WNN puts out in the public eye.
Any level of journalist with the WNN can submit photos with captions and/or full stories to the MDT which can then be uploaded to the News app. Reporters and above can also submit to Twitter via an official WNN account.

**Comment by Montana-77** [comment]
Brought over to discord to discuss and work on the framework.
