### ISSUE TITLE
Diving Gear

### ISSUE THREAD

**Issue by RockemRobotics** [HollywoodHeists/public#69]
The diving gear needs a little something extra to improve it. There is no indicator or timer or gauge or anything to let you know how much air you have. All you get is a really quick notification at the far right of your screen saying you are running out of air, then a handful of seconds later you are out of air and your health drains FAST and you die underwater.

Adding a timer or gauge at the bottom alongside the other status wheels would be fantastic.

**Comment by AliAliJr** [comment]
indicator Added.
