### ISSUE TITLE
Diving for treasure needs a boost

### ISSUE THREAD

**Issue by RockemRobotics** [HollywoodHeists/public#70]
So at minimum, you have to shell out $2500 for diving gear to go treasure diving. You also need other equipment, but a lot of that is reusable, and the diving gear wears out very very quickly.

With a single diving suit, I was able to open three jewelry boxes (although one I didn't get anything out of because I had drifted too far away from the box by the time I completed the skill check) and got two gold watches, which the pawn shop buys for a whopping $293.

So I paid $2500 to make $586. And that's with the high value jewelry boxes! The other crates you can open don't have anything nearly as valuable.

Can this get a boost in some way?

**Comment by Montana-77** [comment]
Cost of gear brought down significantly... items boosted slightly... problem is same items from other robberies so have to be careful with sell prices... will monitor closely and make an adjustment as needed. TY for the post
