### ISSUE TITLE
Map Icons Not Showing Consistently

### ISSUE THREAD

**Issue by wetweebs** [HollywoodHeists/public#76]
disclaimer: low priority and _maybe_ my fault for using NVE

I have only put in a little bit of time so far but as I was trying to get situated and understand how everything was set up I noticed that the icons on the main map would often not show or pop in for just a short time (basically only showing streets and postal). This made it very difficult to figure out what was nearby and what I should try doing first as a new person.

Not sure if other people have had this issue or if it was just me but might be something to look into.

**Comment by Stagonium** [comment]
This is from us having over 100 icons in total on the map, the legend gets messed up after 99, and we are working on reducing the number to alleviate this!

**Comment by AliAliJr** [comment]
Fixed.
