### ISSUE TITLE
Weapon Trafficking Glitch

### ISSUE THREAD

**Issue by MrKyRy** [HollywoodHeists/public#77]
When you go to the island with no cops on you are still able to get weapon crates, when you attempt to bring them over you are sent back to Cayo because no cops are on. However, there is a glitch where you can buy a vehicle and put the cases in the trunk of the vehicle and on reset those vehicles are immediately sent back to mainland impound. You essentially are transporting them back to mainland without any cops and you get away with the case every time.

**Comment by Montana-77** [comment]
Vehicles now return garage on the island. TY!
