### ISSUE TITLE
Logging causing game to crash

### ISSUE THREAD

**Issue by Ghosty19** [HollywoodHeists/public#78]
Heyo!
So when debarking the logs roughly around the 6 or 7th log it causes the game to freeze then crash, I don't know if this has to do with running the animation too much or if it's just taxing on the client due to the animation.
 Just is super frustrating especially with the possibility of your car de-spawning then having to fly into the city to get your car then drive all the way back to Paleto to finish the run.  :)

**Comment by KosimaGhost** [comment]
can confirm, i've crashed so many times already by now T.T
