### ISSUE TITLE
Spawn location When loading in

### ISSUE THREAD

**Issue by MrKennyG** [HollywoodHeists/public#90]
Currently you can spawn at... 
Last Location
Police Department
Legion Square
Paleto Bay
Motels

Can we get an option to spawn inside of the players apartment. And on that note can there be an option for a player to park their car at their apartment so when they spawn there they dont have to go to a garage to pull it out?

**Comment by Montana-77** [comment]
no spawn for players apartments. spawning at your locations of residence coming in the big housing update within the next couple of weeks.
