### ISSUE TITLE
Garbage job cannot be done with more than one person

### ISSUE THREAD

**Issue by MostJabrone22** [HollywoodHeists/public#92]
To my knowledge you aren't able to have multiple people on a garbage run. I think jobs should incentivize and reward you for having more people doing the job together. If I am wrong, I wasn't able to figure out how to get someone else on the same job

**Comment by Montana-77** [comment]
Garbage job would technically be where you both grab bags and split the money at the end.. one person would have the job and the other would only help knock them down... this is being replaced with several MULTIPLAYER Legals that the dev team found a couple of days ago. Be watching for the update :)

**Comment by MostJabrone22** [comment]
Awesome! Yeah, the issue was if you didn't request a job (and get your own truck) you wouldn't be able to grab bags with the person as they would not be on the same trash run as you
