### ISSUE TITLE
Rebel Karin - breaking when taken out of garage

### ISSUE THREAD

**Issue by xxtraspicyy** [HollywoodHeists/public#94]
This is the 4th time that my truck has completely red out on me or broken when taking it out of a garage. 
I was at pdm looking at cars, my truck was parked out front completely not broken had recently fixed it. I go outside and its gone, I ran to impound to remove it from the garage and its in the red for no reason. 
don't think this happens to others im not sure, although incredibly greatful so far for having some free repairs due to this issue happening it'd be great if it didnt especially when there are no mechs on etc don't want to be spending money on something that shouldnt be a thing.

**Comment by MrKyRy** [comment]
My rebel has had the same issue, there are times when I pull it out of the garage with full health and it goes immediately to red.

**Comment by xxtraspicyy** [comment]
> My rebel has had the same issue, there are times when I pull it out of the garage with full health and it goes immediately to red.

good to know I'm not the only one

**Comment by RockemRobotics** [comment]
I had a similar issue before in pre-beta. Take the car to a mechanic. There are aspects to the vehicle that you can't fix with just a repair kit or by taking it to Benny's, and if you leave them the car will break down.

**Comment by xxtraspicyy** [comment]
I've taken it to a mechanic and also done the off duty mechanic repair (toolkit bench) 
Colt has also witnessed the effects of the vehicle being broken his words were "this is literally the worst condition i've ever seen a car in" 
so there's that

**Comment by xxtraspicyy** [comment]
I literally just repaired it at 206 drove it so carefully didnt bump a thing to 204 garage, parked it took it out and its already broken

**Comment by RockemRobotics** [comment]
Sounds almost identical to the issue I'd had before. Had to get it to a mechanic and they needed a bunch of raw metal and stuff to fix it. Had to have it towed there and everything because it was undriveable. It was a while ago, sorry I don't remember more.

**Comment by xxtraspicyy** [comment]
> Sounds almost identical to the issue I'd had before. Had to get it to a mechanic and they needed a bunch of raw metal and stuff to fix it. Had to have it towed there and everything because it was undriveable. It was a while ago, sorry I don't remember more.

yeah, just mentioning it as an ongoing issue, have spoken to colt in city about it but as it continues to happen thought i'd mention it here. 
You're all good preciate the input!

**Comment by KosimaGhost** [comment]
Heya,
To add to the vehicle problemsm this does not happen only with the Rebel.
My Blista seems to randomly break too.
My Audi also keeps changing livery even though I always take it off (putting this here as it's a vehicle issue and I don't wanna crowd the forum). It's not necessarily a huge issue but having to pay 100$ every time i take it out is starting to add up as well.
Thanks all for your hard work ♥

**Comment by Colt-Sterling** [comment]
As much as I've enjoyed having all of y'all stop by 227 to get repairs, we have a fix for this coming soon!
