### ISSUE TITLE
Reduce Paper Pay / Paper Turnout - Thoughts

### ISSUE THREAD

**Issue by MrKyRy** [HollywoodHeists/public#97]
So I know this will not be the most popular thread / post but I believe selling paper for 100 is way too high, it allows for people to get about 10k an hour which compared to all other jobs is over 3x the average pay. I believe paper should be reduced significantly or I think paper should stay the same amount but when you are converting the stripped logs into the paper instead of it being 5 paper I think it should be 2 or 1 instead of 5 to keep all jobs roughly at the same rates. Lets be honest majority of people are grinding only logs and there isnt much RP, its mainly people in grind mode just doing the job that pays the most.

**Comment by montanners0914** [comment]
I disagree. There are a couple of steps you have to do before getting to the paper part, so I believe any legal job should be a higher payout if you have more steps to follow. I also think that no matter what youre going to have times when people are just grinding, not everyone does it 24/7 but there are times where theres only 5 people in the city and they could all be grinding legals.

**Comment by RockemRobotics** [comment]
I don't think the number of steps should matter as much as the amount you can reasonably make per hour of real time. If you can make way more per hour grinding paper than every other job, it's not well balanced.

**Comment by QuintenM911** [comment]
Also for the RP aspect of logging once the city gets bigger BCSO and game wardens will be in and around that area regularly so it won't be empty for long

**Comment by Montana-77** [comment]
yea we are monitoring, definitely will be more on par with the rest of the economy soon.

**Comment by Montana-77** [comment]
Lumbermill took small nerf.
